version: '3.8'

services:
  teomaz-blog:
    container_name: teomaz-blog
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/code/
    ports:
      - 8001:8000
    env_file:
      - envs/docker-env-default.env
    depends_on:
      - teomaz-blog-database

  teomaz-blog-database:
    image: postgres:13-alpine
    volumes:
      - teomaz_postgres_data:/var/lib/postgresql/data/
    env_file:
      - envs/docker-env-default.env
    ports:
      - 5436:5432
volumes:
  postgres_data:
  teomaz_postgres_data:
