version: '3.8'

services:
  teomaz-blog:
    container_name: teomaz-blog
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/code/
    ports:
      - 8000:8000
    environment:
      DEBUG: 0
      DJANGO_ENV: production
      SECRET_KEY: 'uwbm1RwiwsmjMTy574w.VTqR6p1Dwi3FIUVnWrLrK4lOA51cPANri2wzyXDdWQ'
      ALLOWED_HOSTS: localhost 127.0.0.1 [::1] *
      ADMIN_ENABLED: 1
      CORS_ALLOWED_ORIGINS: blog.teomazivil.com
      CORS_ORIGIN_ALLOW_ALL: "True"
      CORS_ALLOW_CREDENTIALS: "True"
      CSRF_TRUSTED_ORIGINS: blog.teomazivil.com
      CORS_REPLACE_HTTPS_REFERER: "True"
      CSRF_COOKIE_DOMAIN: teomazivil.com
      DATABASE: postgres
      POSTGRES_HOST: teomaz-blog-database
      POSTGRES_PORT: 5432
      POSTGRES_USER: mazblog_user
      POSTGRES_PASSWORD: Postgres_password
      POSTGRES_DB: postgres_db

      EMAIL_BACKEND: django.core.mail.backends.smtp.EmailBackend
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USE_TLS: "True"
      EMAIL_HOST_USER: teosweb77@gmail.com
      EMAIL_HOST_PASSWORD: ywvqdfvsgcnaietx
      ACCOUNT_EMAIL_VERIFICATION: none
#    env_file:
#      - envs/docker-env-default.env
    depends_on:
      - teomaz-blog-database

  teomaz-blog-database:
    image: postgres:13-alpine
    volumes:
      - /data/teomaz_postgres_data:/var/lib/postgresql/data/
    env_file:
      - envs/docker-env-default.env
    ports:
      - 5432:5432
volumes:
  postgres_data:
  teomaz_postgres_data:
